services:
  mongodb:
    ports:
      - '127.0.0.1:${MONGODB_PORT:-27017}:27017'

  rabbitmq:
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-reservation}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-reservation}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST:-call-reservation}
    ports:
      - '127.0.0.1:${RABBITMQ_AMQP_PORT:-5672}:5672'
      - '127.0.0.1:${RABBITMQ_MANAGEMENT_PORT:-15672}:15672'

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - '127.0.0.1:${MAILHOG_SMTP_PORT:-1025}:1025'
      - '127.0.0.1:${MAILHOG_HTTP_PORT:-8025}:8025'
    restart: unless-stopped
    networks:
      - backend
